<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "ffpi_firmware_list"
 *
 * Auto generated by Extension Builder 2020-11-30
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'Freifunk Firmware List',
    'description' => 'This extensions offers a frontend Plugin, where you can select FAL Folders. These Folders are then crawled and information like Router Model, Firmware Version and Firmware Type is extracted from the filename. A nice download table is generated with all the information.',
    'category' => 'plugin',
    'author' => 'Kevin Quiatkowski',
    'author_email' => 'kevin@pinneberg.freifunk.net',
    'state' => 'stable',
    'version' => '1.3.2',
    'constraints' => [
        'depends' => [
            'typo3' => '10.0.0-11.4.99',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
